'use client';

interface CaseData {
  citation: string;
  title: string;
  court: string;
  year: number | null;
  judge_name?: string | null;
  summary_en?: string | null;
  summary_ur?: string | null;
  headnotes?: string | null;
  sections_applied?: string | null;
}

export function exportCaseToPDF(caseData: CaseData) {
  const formatCourt = (c: string) => c.replace(/_/g, ' ').replace(/\b\w/g, l => l.toUpperCase());

  const html = `
    <!DOCTYPE html>
    <html>
    <head>
      <title>${caseData.citation} - TVL</title>
      <style>
        * { margin: 0; padding: 0; box-sizing: border-box; }
        body { font-family: 'Georgia', 'Times New Roman', serif; color: #1a1a1a; padding: 40px; max-width: 800px; margin: 0 auto; }
        .header { border-bottom: 2px solid #B8860B; padding-bottom: 20px; margin-bottom: 24px; }
        .brand { font-size: 11px; color: #B8860B; letter-spacing: 3px; text-transform: uppercase; margin-bottom: 12px; }
        .citation { font-family: 'Courier New', monospace; font-size: 14px; font-weight: bold; color: #B8860B; }
        .title { font-size: 20px; font-weight: bold; margin: 8px 0; }
        .meta { font-size: 12px; color: #666; }
        .section { margin-bottom: 24px; }
        .section-title { font-size: 13px; font-weight: bold; color: #B8860B; text-transform: uppercase; letter-spacing: 1px; margin-bottom: 8px; border-bottom: 1px solid #eee; padding-bottom: 4px; }
        .section-content { font-size: 14px; line-height: 1.7; color: #333; }
        .urdu { direction: rtl; text-align: right; font-family: 'Noto Nastaliq Urdu', serif; }
        .badge { display: inline-block; padding: 2px 10px; margin: 2px; font-size: 11px; border: 1px solid #ddd; border-radius: 12px; color: #666; }
        .footer { margin-top: 40px; padding-top: 16px; border-top: 1px solid #eee; font-size: 10px; color: #999; text-align: center; }
        @media print { body { padding: 20px; } }
      </style>
    </head>
    <body>
      <div class="header">
        <div class="brand">TVL — The Value of Law</div>
        <div class="citation">${caseData.citation}</div>
        <div class="title">${caseData.title}</div>
        <div class="meta">
          ${formatCourt(caseData.court)}${caseData.year ? ` (${caseData.year})` : ''}${caseData.judge_name ? ` — ${caseData.judge_name}` : ''}
        </div>
      </div>
      ${caseData.summary_en ? `
        <div class="section">
          <div class="section-title">Summary</div>
          <div class="section-content">${caseData.summary_en}</div>
        </div>
      ` : ''}
      ${caseData.summary_ur ? `
        <div class="section">
          <div class="section-title">خلاصہ (Urdu Summary)</div>
          <div class="section-content urdu">${caseData.summary_ur}</div>
        </div>
      ` : ''}
      ${caseData.headnotes ? `
        <div class="section">
          <div class="section-title">Headnotes</div>
          <div class="section-content">${caseData.headnotes}</div>
        </div>
      ` : ''}
      ${caseData.sections_applied ? `
        <div class="section">
          <div class="section-title">Sections Applied</div>
          <div>${JSON.parse(caseData.sections_applied).map((s: string) => `<span class="badge">${s}</span>`).join('')}</div>
        </div>
      ` : ''}
      <div class="footer">
        Generated by TVL — The Value of Law | According to Spirit Of Law | ${new Date().toLocaleDateString()}
      </div>
    </body>
    </html>
  `;

  const printWindow = window.open('', '_blank');
  if (printWindow) {
    printWindow.document.write(html);
    printWindow.document.close();
    setTimeout(() => printWindow.print(), 500);
  }
}

export function ExportButton({ caseData, className = '' }: { caseData: CaseData; className?: string }) {
  return (
    <button
      onClick={(e) => { e.stopPropagation(); exportCaseToPDF(caseData); }}
      className={`inline-flex items-center gap-1.5 text-xs text-gray-400 hover:text-brass-300 transition-colors ${className}`}
      title="Export as PDF"
    >
      <svg className="w-3.5 h-3.5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M3 16.5v2.25A2.25 2.25 0 005.25 21h13.5A2.25 2.25 0 0021 18.75V16.5M16.5 12L12 16.5m0 0L7.5 12m4.5 4.5V3" />
      </svg>
      <span>Export</span>
    </button>
  );
}
